sudo: false

cache:
  apt: true
  directories:
      - ~/.stack

matrix:
    include:
        - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.4.yaml
          addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
        - env: GHCVER=7.10.2 STACK_YAML=stack-7.10.2.yaml
          addons: {apt: {packages: [ghc-7.10.2], sources: [hvr-ghc]}}
        - env: GHCVER=head STACK_YAML=stack-head.yaml
          addons: {apt: {packages: [ghc-head], sources: [hvr-ghc]}}
    allow_failures:
        - env: GHCVER=head STACK_YAML=stack-head.yaml

before_install:
    - export PATH=/opt/ghc/$GHCVER/bin:$PATH
    - export PATH=~/.local/bin:$PATH
    - mkdir -p ~/.local/bin
    - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-linux-x86_64.tar.gz | gunzip | tar -x
    - mv stack-0.1.6.0-linux-x86_64/stack ~/.local/bin/stack
    - chmod a+x ~/.local/bin/stack
    - ghc --version
    - stack --version

install:
    - ./scripts/travis_long stack --no-terminal --skip-ghc-check setup
    - ./scripts/travis_long stack --no-terminal --skip-ghc-check test --only-snapshot

script:
    - stack --no-terminal --skip-ghc-check test
